# Generated by Django 3.1.14 on 2022-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendance_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sumDay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
