# Generated by Django 3.1.14 on 2022-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendance_sumday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sumDay',
            field=models.DurationField(),
        ),
    ]
