# Generated by Django 3.1.14 on 2022-05-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220523_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sumDay',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
