# Generated by Django 3.1.14 on 2022-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220523_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=True),
        ),
    ]
